### ISSUE TITLE
用这个被学校抓住了

### ISSUE THREAD

**Issue by retaker** [kenvix/health-reporter#1]
校领导说，告诉他我是从哪搞到的这个就可以不受处罚，你耗子尾汁吧

**Comment by kenvix** [comment]
细嗦

**Comment by retaker** [comment]
你好，这个开源项目已经变成历史的眼泪了。

**Comment by kenvix** [comment]
> 你好，这个开源项目已经变成历史的眼泪了。

我想并没有

**Comment by retaker** [comment]
> > 你好，这个开源项目已经变成历史的眼泪了。
> 
> 我想并没有
为什么没有

**Comment by kenvix** [comment]
> > > 你好，这个开源项目已经变成历史的眼泪了。
> > 
> > 我想并没有
> 为什么没有
> 

![722f81b848f029e3.png](https://user-images.githubusercontent.com/4546175/218228519-388817d9-fa87-4237-8ccd-f4bb1bfe4b7b.png)

![-35473e8e08afee0a.png](https://user-images.githubusercontent.com/4546175/218228523-d98851c0-fef1-4105-bbdf-5c2212db5c7a.png)

**Comment by retaker** [comment]
nice to hear
